### ISSUE TITLE
Normalize Column Based on Another

### ISSUE THREAD

**Issue by ddillingham** [oliver-wyman-actuarial/easyr#13]
It allows a user to normalize a column in a dataset from another. Useful when a dataset has been train/test split and normalization should occur off the train data. 

`normalize <- function(newdataf, dataf){
  normalizeddataf <- newdataf 
    normalizeddataf <-  
      (newdataf - min(dataf)) /  (max(dataf) -  min(dataf))
  return(normalizeddataf)
}`

**Comment by superchordate** [comment]
@ddillingham thanks for submitting an idea! One problem though: easyr is meant to be very generic, but this is specific to predictive modeling. My feeling is that this function belongs in a different package. Scott and I would like to build a package for PM, feel free to get that started on BitBucket.

If you agree, please close this issue.
