### ISSUE TITLE
Improve fmat with.unit formatting

### ISSUE THREAD

**Issue by bryce-chamberlain** [oliver-wyman-actuarial/easyr#22]
`fmat(c(250000, 500000, 600000, 1000000), with.unit = TRUE)` returns `"0 M" "0 M" "1 M" "1 M"`. 
It would be better if it was smart enough to add digits in this situation to better tell between the values.

**Comment by superchordate** [comment]
I'm working on a solution to this.

**Comment by bryce-chamberlain** [comment]
https://github.com/oliver-wyman-actuarial/easyr/pull/26
