### ISSUE TITLE
todate not working

### ISSUE THREAD

**Issue by Krishnakumarshrestha** [oliver-wyman-actuarial/easyr#24]
i keep getting this error 

![image](https://user-images.githubusercontent.com/45503377/125657036-4cfa69f5-7847-4500-b333-de57b587fec0.png)

**Comment by bryce-chamberlain** [comment]
Thanks for catching this. Should be fixed with the latest commit. Please update with `devtools::install_github( "oliver-wyman-actuarial/easyr" )`
