### ISSUE TITLE
fldict only scanning one file.

### ISSUE THREAD

**Issue by bryce-chamberlain** [oliver-wyman-actuarial/easyr#25]
Tried to use fldict today and it only ran one file. 

_Sorry I don't have more info readily available. Please let me know if you can't replicate._

**Comment by wilbow** [comment]
Able to reproduce a minimal example:

```
library(easyr)
easyr::begin()
dir.create("tempdatafolder")
write.csv(mtcars, "./tempdatafolder/cars.csv")
write.csv(iris, "./tempdatafolder/iris.csv")

dict <- easyr::fldict(folder = "tempdatafolder")

View(dict)
```

The dictionary only renders for a single file:

![image](https://user-images.githubusercontent.com/101669801/158469726-9d2cc9dd-c694-4dad-a120-6b8d57a2f90e.png)

A test to accompany this fix would:
1. Read in all files in a folder
2. Take the sum of the the number of fields (columns) of all files
3. Check that this matches the number of rows in the dictionary output

**Comment by bryce-chamberlain** [comment]
@DuncanKryszyn ultimately we need to fix this and add a test that verifies the fix, not necessarily in that order. I suggest the steps below:

* Review the information above.
* Use Will's code to replicate the error.
* See if you can work with the fldict function to get it working correctly. Instead of using build-install-test to start, see if you can work with the files directly. This might be easier for you: require(easyr), add your print/browser calls and then source fldict.R to override the version of the function from the R library. This doesn't always work, you may need to source multiple files if fldict calls other files. 
* Once you have it working, add a test that verifies it works properly by running on data files in the folder tests\testthat\test-files and returning information for all the files, not just one. 

Thanks!

**Comment by bryce-chamberlain** [comment]
Resolved with https://github.com/oliver-wyman-actuarial/easyr/pull/33
