### ISSUE TITLE
begin function: Can you add an argument that specifies a file to source?

### ISSUE THREAD

**Issue by ssobel** [oliver-wyman-actuarial/easyr#3]

**Comment by bryce-chamberlain** [comment]
This might involve specifying a path (file or folder) which would be sent to either runfolder() or source(). It might be nice to have it automatically run things in fun/ folders which is a common thing I do.

@ssobel I just realized begin() already runs anything in a functions/ folder but this would still be a really nice feature.

**Comment by brycechamberlain-ow** [comment]
Resolved with https://github.com/oliver-wyman-actuarial/easyr/pull/50
