### ISSUE TITLE
atype date conversion issue

### ISSUE THREAD

**Issue by willdebras** [oliver-wyman-actuarial/easyr#40]
Periodically `easyr::read.any` will produce an error when `auto_convert_dates` is set to `TRUE` (the default handling of `read.any`). In the `atype` function, it seems the `test.conversion` object might get detected as a date in a non-date, string columns, i.e. a comments column where the start of a string includes a date, for example '1/1/2021: here is a comment'.

![image](https://user-images.githubusercontent.com/37971596/193136377-cb23d5bb-ddd0-40dc-901f-eb8312c94398.png)

I propose implementing a trycatch and defaulting back to a string if it fails to convert a column to date.

**Comment by bryce-chamberlain** [comment]
I believe Justin found and fixed this. See https://github.com/oliver-wyman-actuarial/easyr/pull/39. 

Can you install from github to see if that fixes it?

**Comment by willdebras** [comment]
@bryce-chamberlain awesome! Does look like this fixes. Didn't realize Justin had fixed this issue already!
