### ISSUE TITLE
Clipboard memory limit of ecopy too low

### ISSUE THREAD

**Issue by SinisterRobert** [oliver-wyman-actuarial/easyr#43]
The memory limit of ecopy is pretty low, by default utils::write.table can only copy 32 kB of data to the clipboard before the clipboard buffer is full.
I tried to copy a data frame with 58 variables and 3000 rows to examine in Excel and this function gave the warning:

`Warning message:
In utils::write.table(x, file = "clipboard", sep = "\t", row.names = showrowcolnames ==  :
  clipboard buffer is full and output lost`

The clipboard buffer can be increased by changing the `file = "clipboard-___"` parameter where ___ is the number of kB.

Could the clipboard buffer be changed to something larger to accommodate larger data frames?

Thanks!

**Comment by brycechamberlain-ow** [comment]
@SinisterRobert thanks for bringing this up! If you submit a PR, I'll probably merge it.

**Comment by brycechamberlain-ow** [comment]
Plan is to update to 1024 KB (1 MB) and add an argument so the user can expand it as needed.
