### ISSUE TITLE
Fix tobool with custom true and false values.

### ISSUE THREAD

**Issue by bryce-chamberlain** [oliver-wyman-actuarial/easyr#7]
From Brice Richard: The tobool function appears to be providing incorrect output. If I understand the function arguments correctly, both the true.vals and the false.vals arguments allow you to provide a scaler value that can be converted into either a TRUE or a FALSE Boolean value. Having tested this function with varying datasets, sometimes the output returned expected results, and other times it did not. For example, in one of the tests I conducted using 'tobool,' when I passed the following values in this function, as provided below, I received the following feedback:
```
tobool(pheno$sex, true.vals = "F", false.vals = "M")
# easyr::tobool: NAs were created. Returning the vector unchanged. 
# Problematic values include: [ F, F, M, M, F, F ] 
```

**Comment by wilbow** [comment]
I was able to reproduce this error specifically with the "F" and "M". There is some error in `totype.R` that is causing issues specifically to case sensitivity.


This returns a vector of booleans:

```
iris <- dplyr::mutate(iris, binaryExample = ifelse(Species=="versicolor", "f", "m"))
easyr::tobool(iris$binaryExample, true.vals = "f", false.vals = "m")
```

While this returns an error:

```
iris <- dplyr::mutate(iris, binaryExample = ifelse(Species=="versicolor", "F", "M"))
easyr::tobool(iris$binaryExample, true.vals = "F", false.vals = "M")
```

```
easyr::tobool: NAs were created. Returning the vector unchanged. 
  Problematic values include: [ M, M, M, M, M, M ] 
```

Another example:

Passes:
`easyr::tobool(iris$Species, true.vals = unique(iris$Species))
`

Fails:
```
iris$newSpecies = toupper(iris$Species)
easyr::tobool(iris$newSpecies, true.vals = unique(iris$newSpecies)
```

We should write a test that:
1. Checks that tobool is properly returning a boolean vector with one of these working examples
2. Checks that tobool is working with one of the breaking examples

Then we should add in a fix to `totype.R`.

**Comment by bryce-chamberlain** [comment]
@DuncanKryszyn  please review the information above and then:

* Add these 2 tests to the test file, they'll fail at first.
```
# test true and false.
idt = dplyr::mutate(iris, binaryExample = ifelse(Species=="versicolor", "F", "M"))
expect_equal(
    unique(tobool(idt$binaryExample, true.vals = "F", false.vals = "M")),
    c(FALSE, TRUE)
)

# test all-true (this has failed in the past)
idt = iris
idt$newSpecies = toupper(idt $Species)
expect_equal(
    unique(tobool(idt $newSpecies, true.vals = unique(idt$newSpecies)),
    TRUE
)

```

**Comment by bryce-chamberlain** [comment]
Resolved with https://github.com/oliver-wyman-actuarial/easyr/pull/32
